---
title: Pat Dryburgh
description: Pat Dryburgh is a designer based in Vancouver, BC.
email: hello@patdryburgh.com

timezone: '-0800'
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  projects:
    title: Projects
    output: true
    permalink: /work/:name/
    
baseurl: 
url: http://patdryburgh.com
rss: http://feed.patdryburgh.com
json: http://patdryburgh.com/feed/index.json
blog_rss: http://feed.patdryburgh.com/blog
blog_json: http://patdryburgh.com/feed/blog.json
micro_rss: http://feed.patdryburgh.com/micro
micro_json: http://patdryburgh.com/feed/micro.json

twitter: http://twitter.com/patdryburgh
micro_blog: https://micro.blog/pat
instagram: http://instagram.com/patdryburgh

permalink: /:categories/:title/

markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
- jekyll-paginate
- jekyll-redirect-from
- jekyll-autoprefixer

paginate: 20
paginate_path: "/page/:num/"