---
title: Pat Dryburgh
timezone: Africa/Kampala
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  projects:
    title: Projects
    output: true
    permalink: /:collection/:name
email: hello@patdryburgh.com
description: Pat Dryburgh is a product designer based in Vancouver, BC.
baseurl: 
url: http://patdryburgh.com
rss: http://feed.patdryburgh.com
json: http://patdryburgh.com/feed/index.json
blog_rss: http://feed.patdryburgh.com/blog
blog_json: http://patdryburgh.com/feed/blog.json
micro_rss: http://feed.patdryburgh.com/micro
micro_json: http://patdryburgh.com/feed/micro.json
twitter: http://twitter.com/patdryburgh
twitter_username: patdryburgh
github_username: patdryburgh
permalink: "/:categories/:title/"
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
flickr:
  api_key: 9672d2a4458dfb7049545b6a93a0818a
gems:
- jekyll-paginate
