# Site settings
title: Pat Dryburgh
email: hello@patdryburgh.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patdryburgh.com" # the base hostname & protocol for your site
twitter_username: patdryburgh
github_username:  patdryburgh

# Build settings
permalink: /:categories/:title/
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Pagination
paginate: 5
paginate_path: "/blog/page-:num/"